### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by mike-zarandona** [sindresorhus/grunt-ftp#11]
I'm having some trouble downloading from a server.  Here's my configuration:

```
ftpGet: {
	options: {
		host: '*****',
		user: '*****',
		pass: '*****'
	},
	download: {
		files: {
			'public_html/staging/': 'c:/users/mike/google drive/sourcetree/datacede.com/download-folder'
		}
	}
},
```

I have tried every possible variation of specifying the `src` for files (escaping, double back slashes, forward slashes, etc.) but each time I get the error:
```
Running "ftpGet:download" (ftpGet) task
Verifying property ftpGet.download exists in config...OK
Files: c:/users/mike/google drive/sourcetree/datacede.com/download-folder -> public_html/staging/
Options: host="*****", user="*****", pass="*****"
Warning: 550 Can't open c:/users/mike/google drive/sourcetree/datacede.com/download-folder: No such file or directory Use --force to continue.
```

I've also made certain that this folder exists and is writable on my OS.  What am I doing wrong?  I really appreciate the help as this plugin when working will make site deployments super easy.  Cheers.

**Comment by sindresorhus** [comment]
Not really specific to this task. This task just uses the standard grunt APIs to read files.

Try asking on StackOverflow: http://stackoverflow.com/questions/tagged/gruntjs

https://github.com/sindresorhus/grunt-debug-files might be helpful for debugging.
