### ISSUE TITLE
Never uploads more than one file

### ISSUE THREAD

**Issue by alcfeoh** [sindresorhus/grunt-ftp#12]
I'm not sure what's wrong with my config:

      upload: {
        files: {
          '': 'dist/*'
        }
      }

It basically uploads the first file in the dist folder to the server. How to have all files included? Also how to include subfolders and their content recursively?

**Comment by sindresorhus** [comment]
Read the grunt docs. Your config is invalid. How to specify files is the same for all grunt plugins.

**Comment by alcfeoh** [comment]
I'm sorry but the answer is not there: http://gruntjs.com/configuring-tasks
I guess I'm going to switch to a documented plugin.

**Comment by sindresorhus** [comment]
It's right there: http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically

**Comment by alcfeoh** [comment]
Thanks but it was actually faster for me to switch to ftp-deploy, which worked on my first attempt.

**Comment by sindresorhus** [comment]
I don't care what you use, but laziness will get you nowhere. Learn your tools. Read the grunt docs. All of them ;)
