### ISSUE TITLE
there is question about downLoad？

### ISSUE THREAD

**Issue by huangxok** [sindresorhus/grunt-ftp#13]
look，this picture is in grunt
![qq 20151104195440_](https://cloud.githubusercontent.com/assets/7628834/10937505/2dd08a3e-832e-11e5-94ff-7f8c9f5021c2.png)
when i excute grunt fileGet 
there is error 
![image](https://cloud.githubusercontent.com/assets/7628834/10937539/65f72792-832e-11e5-9c52-3e11f823311b.png)
I use the console.log output information in command-line and i know grunt-ftp how to work~
I found that the paramter of ftp.get() function  el.src[0] not exist.so I double right or false,bug?
I don‘t no what a reason 
I am chinese.
PS:FTP:I use local ftp server,OS:win8.1
regards!

**Comment by sindresorhus** [comment]
Both src and destination paths should be relative paths, not absolute.

-

Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)

**Comment by huangxok** [comment]
I am sorry to disturb you again，this  is  my question on stackover
http://stackoverflow.com/questions/33538550/download-file-via-grunt-ftp.
