### ISSUE TITLE
Only one file uploading

### ISSUE THREAD

**Issue by cheshrkat** [sindresorhus/grunt-ftp#8]
With this config:

    ftp: {
        options: {
            host: 'ftp.example.com',
            user: 'username',
            pass: process.env.PW,
            flatten: true
        },
        css: {
            files: {
                'public/css/' : 'source/css/*.css'
            }
        }
    }

...with three css files in /source/css/ locally, I expected to see:
public/css/file1
public/css/file2
public/css/file3

But instead got:
public/css/source/css/file1

I am not totally sure if the path bit is a bug or a misconfiguration, but I've tried lots of options (file patterns, trying to pass the usual options to file, etc) to no avail. Passing the flatten option was a bit of a shot in the dark and appears to do nothing (tried it in the css object as well, also no effect).

Anyway, running grunt with --verbose shows three files detected but only one uploaded:

    Running "ftp:css" (ftp) task
    Verifying property ftp.css exists in config...OK
    Files: source/css/file1.css, source/css/file2.css, source/css/file3.css -> public/css
    Options: host="string", user="string", pass="string", flatten
    Reading source/css/file1.css...OK
    1 file uploaded successfully
    Done, without errors.

Tried these variations:

    'public/css/' : 'source/css/*.css' // result as described
    'public/css/' : 'source/css/*.*' // result as described
    'public/css' : 'source/css/**/*.css' // result as described
    'public/css/' : 'source/css/' // results in Fatal error: Unable to read "source/css/" file (Error code: EISDIR).
    'public' : 'source/css/*.css' // only one file uploaded, to public/source/css

I tried a few different sets of test files and it's always the first file (by filename) that gets uploaded.

Versions:
node v0.10.22
grunt v0.4.5
grunt-ftp v1.0.1
Run from OSX Terminal

Anyway... hopefully it's not just a misconfiguration that I didn't catch, but I'm a bit stumped regardless ;)

**Comment by sindresorhus** [comment]
That's invalid grunt file config. Read the grunt docs for how to do it properly.

http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically

**Comment by cheshrkat** [comment]
FWIW using the config directly from your readme produces the same result (reproducing the directory structure etc - still just the first file).

Thanks for the link - tried both static and dynamic config and both error out or concat the paths, so I'm tossing the task for tonight. Probably just too tired to see it.
